@TmsApi_HostAddress = http://localhost:5294

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results1/
X-Training-User: Tigistu
Accept: application/json
###
GET {{TmsApi_HostAddress}}/payment-options
Accept: application/json

###
GET http://localhost:5294/api/enrollments/worker-smoke

###
GET http://localhost:5294/api/enrollments/test

###
GET http://localhost:5294/api/enrollments/worker-smoke

###
GET http://localhost:5294/api/enrollments

###
curl http://localhost:5294/api/enrollments

###
curl -X POST http://localhost:5294/api/enrollments \
-H "Content-Type: application/json" \
-d '{"studentId":"S-001","courseCode":"CS-101"}'

###
curl http://localhost:5294/api/enrollments/

###
curl -X DELETE http://localhost:5294/api/enrollments/c9b10c9d

###
curl http://localhost:5294/api/enrollments/

###
GET http://localhost:5294/api/error

###
GET http://localhost:5294/scalar/v1

###
GET http://localhost:5294/api/students

###
GET http://localhost:5294/api/courses

###
GET http://localhost:5294/api/courses/CS-101

###
GET http://localhost:5294/api/students/S-001

###
curl http://localhost:5294/api/test/deferred

###
curl http://localhost:5294/api/test/translation-fail

###
http://localhost:5294/api/reports/active-students

###
http://localhost:5294/api/reports/course-enrollments

###
http://localhost:5294/api/reports/average-gpa

###
http://localhost:5294/api/reports/students-no-enrollment-a

###
http://localhost:5294/api/reports/students-no-enrollment-b

###
Get http://localhost:5294/api/students/small-page-response
###
Get http://localhost:5294/api/students/small-page-response?pageNumber=1
###
GET   http://localhost:5294/api/courses/top-5-courses
###
put http://localhost:5294/api/students/1
Content-Type: application/json
###
DELETE http://localhost:5294/api/enrollments/1
Content-Type: application/json
###

curl -X PUT http://localhost:5294/api/enrollments/2/archive

###
Get  http://localhost:5294/scalar/v1
Content-Type:  application/json

###
GET http://localhost:5294/api/courses?page=1&pageSize=10
Accept: application/json

###
GET http://localhost:5294/api/courses?page=3&pageSize=10

###
GET http://localhost:5294/api/courses?pageSize=9999

###
GET http://localhost:5294/api/courses?search=fund

###
GET http://localhost:5294/api/courses?orderBy=Code&descending=true&pageSize=5

###
GET http://localhost:5294/api/courses/1

###
GET http://localhost:5294/api/v2/transcripts/9b48bbf714e8/status
###
curl -i -X POST http://localhost:5294/api/v2/transcripts
-H "Content-Type: application/json"
-H "Idempotency-Key: 11111111-2222-3333-4444-555555555555"
-d '{"studentId": 3}

